Q1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

Q2. Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
list1=list()
list2=list()
l1_size=int(input("list1 size:: "))
for i in range(l1_size):
    p=int(input("Elements::"))
    list1.append(p)
print('list1:',list1)
l2_size=int(input("list2 size:: "))
for i in range(l2_size):
    q=int(input("Elements::"))
    list2.append(q)
print('list2:',list2)

print("convert list into np array")
np1= np.array(list1)
np2=np.array(list2)
print("array1:", np1)
print("array2:",np2)

print("concatenate arrays")
print(np.concatenate((np1,np2),axis=0))

print("sort arrays")
print(np.sort(np1))
print(np.sort(np2))



list1 size:: 3
Elements::3
Elements::1
Elements::2
list1: [3, 1, 2]
list2 size:: 3
Elements::6
Elements::5
Elements::7
list2: [6, 5, 7]
convert list into np array
array1: [3 1 2]
array2: [6 5 7]
concatenate arrays
[3 1 2 6 5 7]
sort arrays
[1 2 3]
[5 6 7]


q3. Write a code snippet to find the dimensions of a ndarray and its size.

In [12]:
a = np.array([[1,2],[3,4]])
arr_shape = a.shape
arr_dim = a.ndim
arr_size = a.size
print("dimension:",arr_dim)
print("shape:",arr_shape)
print("size:",arr_size)

dimension: 2
shape: (2, 2)
size: 4


q4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [29]:
x1d = np.array([1,2,3,4,5,6])
#x2d = np.reshape(x1d,(2, 3))
#print(x2d)
x2d_new= x1d[:, np.newaxis]
print(x2d_new)
print("************")
expand_dims = np.expand_dims(x1d, axis=(0,1))
print(expand_dims)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
************
[[[1 2 3 4 5 6]]]


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [37]:
arr1 =np.array([[1,2],[3,4]]) 
print ("arr1 : \n", arr1) 
  
arr2 = np.array([[5,6],[7,8]]) 
print ("arr2 : \n ", arr2) 

print("************")
print("vertical stack: \n", np.vstack((arr1,arr2)))
print("Horizontal stack: \n",np.hstack((arr1,arr2)))

arr1 : 
 [[1 2]
 [3 4]]
arr2 : 
  [[5 6]
 [7 8]]
************
vertical stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack: 
 [[1 2 5 6]
 [3 4 7 8]]


Questions 6:
How to get unique items and counts of unique items?

In [43]:
#consider taking a list

def unique(a_list):
    x = np.array(a_list)
    print(np.unique(x))
    
a_list = [7,8,7,9,9,11,12,12]
print("the unique values from a_list is:")
unique(a_list)

l1=[]
count=0
for item in a_list:
    if item not in l1:
        count = count+1
        l1.append(item)
print("no.of unique items are: ", count)
    

    


the unique values from a_list is:
[ 7  8  9 11 12]
no.of unique items are:  5
